### ISSUE TITLE
How do I mine.

### ISSUE THREAD

**Issue by imansour12** [acejr1337/TerryDavisCoin#3]
Hey, 
I tried looking through the repo but i couldn't find anything about mining.
Is there any documentation I didn't see?

**Comment by acejr1337** [comment]
Hi, you can use any scrypt mining software such as CGMiner or SGMiner to
mine either solo or in a joined pool.
You can use https://miningcoin.ca/ as they offer a public pool.
If you require any more help pop into our discord and someone will be able
to help you further :)
Good luck

**Comment by imansour12** [comment]
Thanks :))
